import {useRouter} from "next/router";
import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function CoffeeStore(props){
    const router = useRouter();

    return <div>
        <Head>
            <title className={styles.title}>{`Page ${router.query?.dynamic}`}
            </title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        Page {router.query?.dynamic}
        <br/>
        <Link href={"/"}>
            <a>Go home</a>
        </Link>
    </div>
}
