import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";

export default function Home() {
    const handleOnBannerClick = () => {
        console.log('Hi Banner button');
    }

    return (
        <div className={styles.container}>
            <Head>
                <title className={styles.title}>Coffee Connoisseur</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <Banner buttonText={"View stores nearby"} handleOnClick={handleOnBannerClick}/>
            </main>
        </div>
    )
}
